echo  "clear all;"
echo  "format long;"
echo  "au2kcal = 627.50957099203276;"
echo  "% NH3_C3_O_comp"              
B=$(grep -B6 'ORCA prop' C1L1A1/B.out | grep FINAL | awk {'print $NF'})
D=$(grep -B6 'ORCA prop' C1L1A1/D1.out | grep FINAL | awk {'print $NF'})
Ap=$(grep -B6 'ORCA prop' C1L1A1/A_pos.out | grep FINAL | awk {'print $NF'})
Am=$(grep -B6 'ORCA prop' C1L1A1/A_neg.out | grep FINAL | awk {'print $NF'})
Cp=$(grep -B6 'ORCA prop' C1L1A1/C1_pos.out | grep FINAL | awk {'print $NF'})
Cm=$(grep -B6 'ORCA prop' C1L1A1/C1_neg.out | grep FINAL | awk {'print $NF'})
echo  "B = $B;"
echo  "D = $D;"
echo  "A = $Ap $Am;"
echo  "C = $Cp $Cm;"
echo  "r = 4.674;"
echo  "E_NH3_C3_O = ((B - D) - (A - C))*au2kcal;"
echo  "Electro_NH3_C3_O = -0.529*au2kcal/r;"
echo  "E_NH3_C3_O_TC = E_NH3_C3_O %+ Electro_NH3_C3_O"
echo  "% NH3_C6_O_comp"
B=$(grep -B6 'ORCA prop' C1L2A1/B.out | grep FINAL | awk {'print $NF'})
D=$(grep -B6 'ORCA prop' C1L2A1/D1.out | grep FINAL | awk {'print $NF'})
Ap=$(grep -B6 'ORCA prop' C1L2A1/A_pos.out | grep FINAL | awk {'print $NF'})
Am=$(grep -B6 'ORCA prop' C1L2A1/A_neg.out | grep FINAL | awk {'print $NF'})
Cp=$(grep -B6 'ORCA prop' C1L2A1/C1_pos.out | grep FINAL | awk {'print $NF'})
Cm=$(grep -B6 'ORCA prop' C1L2A1/C1_neg.out | grep FINAL | awk {'print $NF'})
echo  "B = $B;"
echo  "D = $D;"
echo  "A = $Ap $Am;"
echo  "C = $Cp $Cm;"
echo  "r = 8.537;"
echo  "E_NH3_C6_O = ((B - D) - (A - C))*au2kcal;"
echo  "Electro_NH3_C6_O = -0.529*au2kcal/r;"
echo  "E_NH3_C6_O_TC = E_NH3_C6_O %+ Electro_NH3_C6_O"
echo  "% NH3_C9_O_comp"       
B=$(grep -B6 'ORCA prop' C1L3A1/B.out | grep FINAL | awk {'print $NF'})
D=$(grep -B6 'ORCA prop' C1L3A1/D1.out | grep FINAL | awk {'print $NF'})
Ap=$(grep -B6 'ORCA prop' C1L3A1/A_pos.out | grep FINAL | awk {'print $NF'})
Am=$(grep -B6 'ORCA prop' C1L3A1/A_neg.out | grep FINAL | awk {'print $NF'})
Cp=$(grep -B6 'ORCA prop' C1L3A1/C1_pos.out | grep FINAL | awk {'print $NF'})
Cm=$(grep -B6 'ORCA prop' C1L3A1/C1_neg.out | grep FINAL | awk {'print $NF'})
echo  "B = $B;"
echo  "D = $D;"
echo  "A = $Ap $Am;"
echo  "C = $Cp $Cm;"
echo  "r = 11.409;"
echo  "E_NH3_C9_O = ((B - D) - (A - C))*au2kcal;"
echo  "Electro_NH3_C9_O = -0.529*au2kcal/r;"
echo  "E_NH3_C9_O_TC = E_NH3_C9_O %+ Electro_NH3_C9_O"
echo  "% Guanidinium_O_C6_O_comp"
 B=$(grep -B6 'ORCA prop' C2L2A1/B.out | grep FINAL | awk {'print $NF'})
D1=$(grep -B6 'ORCA prop' C2L2A1/D1.out | grep FINAL | awk {'print $NF'})
D2=$(grep -B6 'ORCA prop' C2L2A1/D2.out | grep FINAL | awk {'print $NF'})
Ap=$(grep -B6 'ORCA prop' C2L2A1/A_pos.out | grep FINAL | awk {'print $NF'})
Am=$(grep -B6 'ORCA prop' C2L2A1/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C2L2A1/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C2L2A1/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C2L2A1/C2_pos.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C2p $C1m;"
echo  " r = 8.569;"
echo  "E_Guanidinium_O_C6_O_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_O_C6_O_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "Electro_Guanidinium_O_C6_O = -0.529*au2kcal/r;"
echo  "E_SB = [E_Guanidinium_O_C6_O_1 E_Guanidinium_O_C6_O_2];"
echo  "E_Guanidinium_O_C6_O_TC = mean(E_SB) %+ Electro_Guanidinium_O_C6_O"
echo  "% Guanidinium_O_C9_O_comp     "
  B=$(grep -B6 'ORCA prop' C2L3A1/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C2L3A1/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C2L3A1/D2.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C2L3A1/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C2L3A1/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C2L3A1/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C2L3A1/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C2L3A1/C2_pos.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C2p $C1m;"
echo  " r = 12.320;"
echo  "E_Guanidinium_O_C9_O_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_O_C9_O_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "Electro_Guanidinium_O_C9_O = -0.529*au2kcal/r;"
echo  "E_SB = [E_Guanidinium_O_C9_O_1 E_Guanidinium_O_C9_O_2];"
echo  "E_Guanidinium_O_C9_O_TC = mean(E_SB) %+ Electro_Guanidinium_O_C9_O"
echo  "% Guanidinium_C3_O_comp "
  B=$(grep -B6 'ORCA prop' C3L1A1/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C3L1A1/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C3L1A1/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C3L1A1/D3.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C3L1A1/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C3L1A1/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C3L1A1/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C3L1A1/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C3L1A1/C2_pos.out | grep FINAL | awk {'print $NF'})
C3p=$(grep -B6 'ORCA prop' C3L1A1/C3_pos.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C2p $C1m;"
echo  "C3 = $C3p $C1m;"
echo  " r = 5.115;"
echo  "E_Guanidinium_C3_O_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_C3_O_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_Guanidinium_C3_O_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "Electro_Guanidinium_C3_O = -0.529*au2kcal/r;"
echo  "E_SB = [E_Guanidinium_C3_O_1 E_Guanidinium_C3_O_2 E_Guanidinium_C3_O_3];"
echo  "E_Guanidinium_C3_O_TC = mean(E_SB) %+ Electro_Guanidinium_C3_O"
echo  "% Guanidinium_C6_O_comp     "
  B=$(grep -B6 'ORCA prop' C3L2A1/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C3L2A1/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C3L2A1/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C3L2A1/D3.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C3L2A1/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C3L2A1/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C3L2A1/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C3L2A1/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C3L2A1/C2_pos.out | grep FINAL | awk {'print $NF'})
C3p=$(grep -B6 'ORCA prop' C3L2A1/C3_pos.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C2p $C1m;"
echo  "C3 = $C3p $C1m;"
echo  " r = 8.830;"
echo  "E_Guanidinium_C6_O_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_C6_O_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_Guanidinium_C6_O_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "Electro_Guanidinium_C6_O = -0.529*au2kcal/r;"
echo  "E_SB = [E_Guanidinium_C6_O_1 E_Guanidinium_C6_O_2 E_Guanidinium_C6_O_3];"
echo  "E_Guanidinium_C6_O_TC = mean(E_SB) %+ Electro_Guanidinium_C6_O"
echo  "% Guanidinium_C9_O_comp "     
  B=$(grep -B6 'ORCA prop' C3L3A1/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C3L3A1/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C3L3A1/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C3L3A1/D3.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C3L3A1/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C3L3A1/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C3L3A1/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C3L3A1/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C3L3A1/C2_pos.out | grep FINAL | awk {'print $NF'})
C3p=$(grep -B6 'ORCA prop' C3L3A1/C3_pos.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C2p $C1m;"
echo  "C3 = $C3p $C1m;"
echo  " r = 10.162;"
echo  "E_Guanidinium_C9_O_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_C9_O_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_Guanidinium_C9_O_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "Electro_Guanidinium_C9_O = -0.529*au2kcal/r;"
echo  "E_SB = [E_Guanidinium_C9_O_1 E_Guanidinium_C9_O_2 E_Guanidinium_C9_O_3];"
echo  "E_Guanidinium_C9_O_TC = mean(E_SB) %+ Electro_Guanidinium_C9_O"
echo  "% NH3_C3_COO_comp "     
  B=$(grep -B6 'ORCA prop' C1L1A2/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C1L1A2/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C1L1A2/D2.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C1L1A2/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C1L1A2/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C1L1A2/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C1L1A2/C1_neg.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C1L1A2/C2_neg.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C1p $C2m;"
echo  " r = 4.925;"
echo  "E_NH3_C3_COO_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_NH3_C3_COO_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "Electro_NH3_C3_COO = -0.529*au2kcal/r;"
echo  "E_SB = [E_NH3_C3_COO_1 E_NH3_C3_COO_2];"
echo  "E_NH3_C3_COO_TC = mean(E_SB) %+ Electro_NH3_C3_COO"
echo  "% NH3_C6_COO_comp  "
  B=$(grep -B6 'ORCA prop' C1L2A2/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C1L2A2/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C1L2A2/D2.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C1L2A2/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C1L2A2/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C1L2A2/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C1L2A2/C1_neg.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C1L2A2/C2_neg.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C1p $C2m;"
echo  " r = 7.974;"
echo  "E_NH3_C6_COO_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_NH3_C6_COO_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "Electro_NH3_C6_COO = -0.529*au2kcal/r;"
echo  "E_SB = [E_NH3_C6_COO_1 E_NH3_C6_COO_2];"
echo  "E_NH3_C6_COO_TC = mean(E_SB) %+ Electro_NH3_C6_COO"
echo  "% NH3_C9_COO_comp "
  B=$(grep -B6 'ORCA prop' C1L3A2/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C1L3A2/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C1L3A2/D2.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C1L3A2/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C1L3A2/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C1L3A2/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C1L3A2/C1_neg.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C1L3A2/C2_neg.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C1p $C2m;"
echo  " r = 11.590;"
echo  "E_NH3_C9_COO_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_NH3_C9_COO_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "Electro_NH3_C9_COO = -0.529*au2kcal/r;"
echo  "E_SB = [E_NH3_C9_COO_1 E_NH3_C9_COO_2];"
echo  "E_NH3_C9_COO_TC = mean(E_SB) %+ Electro_NH3_C9_COO"
echo  "% Guanidinium_O_C3_COO_comp1  "
  B=$(grep -B6 'ORCA prop' C2L1A2/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C2L1A2/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C2L1A2/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C2L1A2/D3.out | grep FINAL | awk {'print $NF'})
 D4=$(grep -B6 'ORCA prop' C2L1A2/D4.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C2L1A2/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C2L1A2/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C2L1A2/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C2L1A2/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C2L1A2/C2_pos.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C2L1A2/C2_neg.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  "D4 = $D4;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C2p $C1m;"
echo  "C3 = $C1p $C2m;"
echo  "C4 = $C2p $C2m;"
echo  " r = 4.965;"
echo  "E_Guanidinium_O_C3_COO_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_O_C3_COO_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_Guanidinium_O_C3_COO_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "E_Guanidinium_O_C3_COO_4 = ((B - D4) - (A - C4))*au2kcal;"
echo  "E_SB = [E_Guanidinium_O_C3_COO_1 E_Guanidinium_O_C3_COO_2 E_Guanidinium_O_C3_COO_3 E_Guanidinium_O_C3_COO_4];"
echo  "Electro_Guanidinium_O_C3_COO = -0.529*au2kcal/r;"
echo  "E_Guanidinium_O_C3_COO_TC = mean(E_SB) %+ Electro_Guanidinium_O_C3_COO"
echo  "% Guanidinium_O_C6_COO_comp1  "
  B=$(grep -B6 'ORCA prop' C2L2A2/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C2L2A2/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C2L2A2/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C2L2A2/D3.out | grep FINAL | awk {'print $NF'})
 D4=$(grep -B6 'ORCA prop' C2L2A2/D4.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C2L2A2/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C2L2A2/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C2L2A2/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C2L2A2/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C2L2A2/C2_pos.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C2L2A2/C2_neg.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  "D4 = $D4;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C2p $C1m;"
echo  "C3 = $C1p $C2m;"
echo  "C4 = $C2p $C2m;"
echo  " r = 8.901;"
echo  "E_Guanidinium_O_C6_COO_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_O_C6_COO_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_Guanidinium_O_C6_COO_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "E_Guanidinium_O_C6_COO_4 = ((B - D4) - (A - C4))*au2kcal;"
echo  "E_SB = [E_Guanidinium_O_C6_COO_1 E_Guanidinium_O_C6_COO_2 E_Guanidinium_O_C6_COO_3 E_Guanidinium_O_C6_COO_4];"
echo  "Electro_Guanidinium_O_C6_COO = -0.529*au2kcal/r;"
echo  "E_Guanidinium_O_C6_COO_TC = mean(E_SB) %+ Electro_Guanidinium_O_C6_COO"
echo  "% Guanidinium_O_C9_COO_comp1   "
  B=$(grep -B6 'ORCA prop' C2L3A2/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C2L3A2/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C2L3A2/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C2L3A2/D3.out | grep FINAL | awk {'print $NF'})
 D4=$(grep -B6 'ORCA prop' C2L3A2/D4.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C2L3A2/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C2L3A2/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C2L3A2/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C2L3A2/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C2L3A2/C2_pos.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C2L3A2/C2_neg.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  "D4 = $D4;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;" 
echo  "C2 = $C2p $C1m;"
echo  "C3 = $C1p $C2m;"
echo  "C4 = $C2p $C2m;"
echo  " r = 12.579;"
echo  "E_Guanidinium_O_C9_COO_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_O_C9_COO_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_Guanidinium_O_C9_COO_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "E_Guanidinium_O_C9_COO_4 = ((B - D4) - (A - C4))*au2kcal;"
echo  "Electro_Guanidinium_O_C9_COO = -0.529*au2kcal/r;"
echo  "E_SB = [E_Guanidinium_O_C9_COO_1 E_Guanidinium_O_C9_COO_2 E_Guanidinium_O_C9_COO_3 E_Guanidinium_O_C9_COO_4];"
echo  "E_Guanidinium_O_C9_COO_TC = mean(E_SB) %+ Electro_Guanidinium_O_C9_COO"
echo  "% Guanidinium_C3_COO_comp  "
  B=$(grep -B6 'ORCA prop' C3L1A2/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C3L1A2/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C3L1A2/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C3L1A2/D3.out | grep FINAL | awk {'print $NF'})
 D4=$(grep -B6 'ORCA prop' C3L1A2/D4.out | grep FINAL | awk {'print $NF'})
 D5=$(grep -B6 'ORCA prop' C3L1A2/D5.out | grep FINAL | awk {'print $NF'})
 D6=$(grep -B6 'ORCA prop' C3L1A2/D6.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C3L1A2/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C3L1A2/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C3L1A2/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C3L1A2/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C3L1A2/C2_pos.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C3L1A2/C2_neg.out | grep FINAL | awk {'print $NF'})
C3p=$(grep -B6 'ORCA prop' C3L1A2/C3_pos.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  "D4 = $D4;"
echo  "D5 = $D5;"
echo  "D6 = $D6;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C2p $C1m;"
echo  "C3 = $C3p $C1m;"
echo  "C4 = $C1p $C2m;"
echo  "C5 = $C2p $C2m;"
echo  "C6 = $C3p $C2m;"
echo  " r = 6.247;"
echo  "E_Guanidinium_C3_COO_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_C3_COO_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_Guanidinium_C3_COO_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "E_Guanidinium_C3_COO_4 = ((B - D4) - (A - C4))*au2kcal;"
echo  "E_Guanidinium_C3_COO_5 = ((B - D5) - (A - C5))*au2kcal;"
echo  "E_Guanidinium_C3_COO_6 = ((B - D6) - (A - C6))*au2kcal;"
echo  "Electro_Guanidinium_C3_COO = -0.529*au2kcal/r;"
echo  "E_SB = [E_Guanidinium_C3_COO_1 E_Guanidinium_C3_COO_2 E_Guanidinium_C3_COO_3 E_Guanidinium_C3_COO_4 E_Guanidinium_C3_COO_5 E_Guanidinium_C3_COO_6];"
echo  "E_Guanidinium_C3_COO_TC = mean(E_SB) %+ Electro_Guanidinium_C3_COO"
echo  "% Guanidinium_C6_COO_comp     "
  B=$(grep -B6 'ORCA prop' C3L2A2/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C3L2A2/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C3L2A2/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C3L2A2/D3.out | grep FINAL | awk {'print $NF'})
 D4=$(grep -B6 'ORCA prop' C3L2A2/D4.out | grep FINAL | awk {'print $NF'})
 D5=$(grep -B6 'ORCA prop' C3L2A2/D5.out | grep FINAL | awk {'print $NF'})
 D6=$(grep -B6 'ORCA prop' C3L2A2/D6.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C3L2A2/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C3L2A2/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C3L2A2/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C3L2A2/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C3L2A2/C2_pos.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C3L2A2/C2_neg.out | grep FINAL | awk {'print $NF'})
C3p=$(grep -B6 'ORCA prop' C3L2A2/C3_pos.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  "D4 = $D4;"
echo  "D5 = $D5;"
echo  "D6 = $D6;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C2p $C1m;"
echo  "C3 = $C3p $C1m;"
echo  "C4 = $C1p $C2m;"
echo  "C5 = $C2p $C2m;"
echo  "C6 = $C3p $C2m;"
echo  " r = 10.043;"
echo  "E_Guanidinium_C6_COO_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_C6_COO_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_Guanidinium_C6_COO_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "E_Guanidinium_C6_COO_4 = ((B - D4) - (A - C4))*au2kcal;"
echo  "E_Guanidinium_C6_COO_5 = ((B - D5) - (A - C5))*au2kcal;"
echo  "E_Guanidinium_C6_COO_6 = ((B - D6) - (A - C6))*au2kcal;"
echo  "Electro_Guanidinium_C6_COO = -0.529*au2kcal/r;"
echo  "E_SB = [E_Guanidinium_C6_COO_1 E_Guanidinium_C6_COO_2 E_Guanidinium_C6_COO_3 E_Guanidinium_C6_COO_4 E_Guanidinium_C6_COO_5 E_Guanidinium_C6_COO_6];"
echo  "E_Guanidinium_C6_COO_TC = mean(E_SB) %+ Electro_Guanidinium_C6_COO"
echo  "% Guanidinium_C9_COO_comp     "
  B=$(grep -B6 'ORCA prop' C3L3A2/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C3L3A2/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C3L3A2/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C3L3A2/D3.out | grep FINAL | awk {'print $NF'})
 D4=$(grep -B6 'ORCA prop' C3L3A2/D4.out | grep FINAL | awk {'print $NF'})
 D5=$(grep -B6 'ORCA prop' C3L3A2/D5.out | grep FINAL | awk {'print $NF'})
 D6=$(grep -B6 'ORCA prop' C3L3A2/D6.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C3L3A2/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C3L3A2/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C3L3A2/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C3L3A2/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C3L3A2/C2_pos.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C3L3A2/C2_neg.out | grep FINAL | awk {'print $NF'})
C3p=$(grep -B6 'ORCA prop' C3L3A2/C3_pos.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  "D4 = $D4;"
echo  "D5 = $D5;"
echo  "D6 = $D6;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C2p $C1m;"
echo  "C3 = $C3p $C1m;"
echo  "C4 = $C1p $C2m;"
echo  "C5 = $C2p $C2m;"
echo  "C6 = $C3p $C2m;"
echo  " r = 13.850;"
echo  "E_Guanidinium_C9_COO_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_C9_COO_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_Guanidinium_C9_COO_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "E_Guanidinium_C9_COO_4 = ((B - D4) - (A - C4))*au2kcal;"
echo  "E_Guanidinium_C9_COO_5 = ((B - D5) - (A - C5))*au2kcal;"
echo  "E_Guanidinium_C9_COO_6 = ((B - D6) - (A - C6))*au2kcal;"
echo  "Electro_Guanidinium_C9_COO = -0.529*au2kcal/r;"
echo  "E_SB = [E_Guanidinium_C9_COO_1 E_Guanidinium_C9_COO_2 E_Guanidinium_C9_COO_3 E_Guanidinium_C9_COO_4 E_Guanidinium_C9_COO_5 E_Guanidinium_C9_COO_6];"
echo  "E_Guanidinium_C9_COO_TC = mean(E_SB) %+ Electro_Guanidinium_C9_COO"
echo  "% NH3_C3_SO3_comp"
  B=$(grep -B6 'ORCA prop' C1L1A3/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C1L1A3/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C1L1A3/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C1L1A3/D3.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C1L1A3/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C1L1A3/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C1L1A3/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C1L1A3/C1_neg.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C1L1A3/C2_neg.out | grep FINAL | awk {'print $NF'})
C3m=$(grep -B6 'ORCA prop' C1L1A3/C3_neg.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C1p $C2m;"
echo  "C3 = $C1p $C3m;"
echo  " r = 5.111;"
echo  "E_NH3_C3_SO3_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_NH3_C3_SO3_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_NH3_C3_SO3_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "Electro_NH3_C3_SO3 = -0.529*au2kcal/r;"
echo  "E_SB = [E_NH3_C3_SO3_1 E_NH3_C3_SO3_2 E_NH3_C3_SO3_3];"
echo  "E_NH3_C3_SO3_TC = mean(E_SB) %+ Electro_NH3_C3_SO3"
echo  "% NH3_C6_SO3_comp"
  B=$(grep -B6 'ORCA prop' C1L2A3/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C1L2A3/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C1L2A3/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C1L2A3/D3.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C1L2A3/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C1L2A3/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C1L2A3/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C1L2A3/C1_neg.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C1L2A3/C2_neg.out | grep FINAL | awk {'print $NF'})
C3m=$(grep -B6 'ORCA prop' C1L2A3/C3_neg.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C1p $C2m;"
echo  "C3 = $C1p $C3m;"
echo  " r = 9.000;"
echo  "E_NH3_C6_SO3_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_NH3_C6_SO3_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_NH3_C6_SO3_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "Electro_NH3_C6_SO3 = -0.529*au2kcal/r;"
echo  "E_SB = [E_NH3_C6_SO3_1 E_NH3_C6_SO3_2 E_NH3_C6_SO3_3];"
echo  "E_NH3_C6_SO3_TC = mean(E_SB) %+ Electro_NH3_C6_SO3"
echo  "% NH3_C9_SO3_comp "
  B=$(grep -B6 'ORCA prop' C1L3A3/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C1L3A3/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C1L3A3/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C1L3A3/D3.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C1L3A3/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C1L3A3/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C1L3A3/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C1L3A3/C1_neg.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C1L3A3/C2_neg.out | grep FINAL | awk {'print $NF'})
C3m=$(grep -B6 'ORCA prop' C1L3A3/C3_neg.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C1p $C2m;"
echo  "C3 = $C1p $C3m;"
echo  " r = 12.722;"
echo  "E_NH3_C9_SO3_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_NH3_C9_SO3_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_NH3_C9_SO3_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "Electro_NH3_C9_SO3 = -0.529*au2kcal/r;"
echo  "E_SB = [E_NH3_C9_SO3_1 E_NH3_C9_SO3_2 E_NH3_C9_SO3_3];"
echo  "E_NH3_C9_SO3_TC = mean(E_SB) %+ Electro_NH3_C9_SO3"
echo  "% Guanidinium_O_C3_SO3_comp1   "
  B=$(grep -B6 'ORCA prop' C2L1A3/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C2L1A3/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C2L1A3/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C2L1A3/D3.out | grep FINAL | awk {'print $NF'})
 D4=$(grep -B6 'ORCA prop' C2L1A3/D4.out | grep FINAL | awk {'print $NF'})
 D5=$(grep -B6 'ORCA prop' C2L1A3/D5.out | grep FINAL | awk {'print $NF'})
 D6=$(grep -B6 'ORCA prop' C2L1A3/D6.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C2L1A3/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C2L1A3/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C2L1A3/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C2L1A3/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C2L1A3/C2_pos.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C2L1A3/C2_neg.out | grep FINAL | awk {'print $NF'})
C3m=$(grep -B6 'ORCA prop' C2L1A3/C3_neg.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  "D4 = $D4;"
echo  "D5 = $D5;"
echo  "D6 = $D6;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C2p $C1m;"
echo  "C3 = $C1p $C2m;"
echo  "C4 = $C2p $C2m;"
echo  "C5 = $C1p $C3m;"
echo  "C6 = $C2p $C3m;"
echo  " r = 5.217;"
echo  "E_Guanidinium_O_C3_SO3_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_O_C3_SO3_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_Guanidinium_O_C3_SO3_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "E_Guanidinium_O_C3_SO3_4 = ((B - D4) - (A - C4))*au2kcal;"
echo  "E_Guanidinium_O_C3_SO3_5 = ((B - D5) - (A - C5))*au2kcal;"
echo  "E_Guanidinium_O_C3_SO3_6 = ((B - D6) - (A - C6))*au2kcal;"
echo  "Electro_Guanidinium_O_C3_SO3 = -0.529*au2kcal/r;"
echo  "E_SB = [E_Guanidinium_O_C3_SO3_1 E_Guanidinium_O_C3_SO3_2 E_Guanidinium_O_C3_SO3_3 E_Guanidinium_O_C3_SO3_4 E_Guanidinium_O_C3_SO3_5 E_Guanidinium_O_C3_SO3_6];"
echo  "E_Guanidinium_O_C3_SO3_TC = mean(E_SB) %+ Electro_Guanidinium_O_C3_SO3"
echo  "% Guanidinium_O_C6_SO3_comp1    "
  B=$(grep -B6 'ORCA prop' C2L2A3/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C2L2A3/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C2L2A3/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C2L2A3/D3.out | grep FINAL | awk {'print $NF'})
 D4=$(grep -B6 'ORCA prop' C2L2A3/D4.out | grep FINAL | awk {'print $NF'})
 D5=$(grep -B6 'ORCA prop' C2L2A3/D5.out | grep FINAL | awk {'print $NF'})
 D6=$(grep -B6 'ORCA prop' C2L2A3/D6.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C2L2A3/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C2L2A3/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C2L2A3/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C2L2A3/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C2L2A3/C2_pos.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C2L2A3/C2_neg.out | grep FINAL | awk {'print $NF'})
C3m=$(grep -B6 'ORCA prop' C2L2A3/C3_neg.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  "D4 = $D4;"
echo  "D5 = $D5;"
echo  "D6 = $D6;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;" 
echo  "C2 = $C2p $C1m;"
echo  "C3 = $C1p $C2m;"
echo  "C4 = $C2p $C2m;"
echo  "C5 = $C1p $C3m;"
echo  "C6 = $C2p $C3m;"
echo  " r = 9.032;"
echo  "E_Guanidinium_O_C6_SO3_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_O_C6_SO3_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_Guanidinium_O_C6_SO3_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "E_Guanidinium_O_C6_SO3_4 = ((B - D4) - (A - C4))*au2kcal;"
echo  "E_Guanidinium_O_C6_SO3_5 = ((B - D5) - (A - C5))*au2kcal;"
echo  "E_Guanidinium_O_C6_SO3_6 = ((B - D6) - (A - C6))*au2kcal;"
echo  "Electro_Guanidinium_O_C6_SO3 = -0.529*au2kcal/r;"
echo  "E_SB = [E_Guanidinium_O_C6_SO3_1 E_Guanidinium_O_C6_SO3_2 E_Guanidinium_O_C6_SO3_3 E_Guanidinium_O_C6_SO3_4 E_Guanidinium_O_C6_SO3_5 E_Guanidinium_O_C6_SO3_6];"
echo  "E_Guanidinium_O_C6_SO3_TC = mean(E_SB) %+ Electro_Guanidinium_O_C6_SO3"
echo  "% Guanidinium_O_C9_SO3_comp1 "
  B=$(grep -B6 'ORCA prop' C2L3A3/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C2L3A3/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C2L3A3/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C2L3A3/D3.out | grep FINAL | awk {'print $NF'})
 D4=$(grep -B6 'ORCA prop' C2L3A3/D4.out | grep FINAL | awk {'print $NF'})
 D5=$(grep -B6 'ORCA prop' C2L3A3/D5.out | grep FINAL | awk {'print $NF'})
 D6=$(grep -B6 'ORCA prop' C2L3A3/D6.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C2L3A3/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C2L3A3/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C2L3A3/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C2L3A3/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C2L3A3/C2_pos.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C2L3A3/C2_neg.out | grep FINAL | awk {'print $NF'})
C3m=$(grep -B6 'ORCA prop' C2L3A3/C3_neg.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  "D4 = $D4;"
echo  "D5 = $D5;"
echo  "D6 = $D6;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C2p $C1m;"
echo  "C3 = $C1p $C2m;"
echo  "C4 = $C2p $C2m;"
echo  "C5 = $C1p $C3m;"
echo  "C6 = $C2p $C3m;"
echo  " r = 12.748;"
echo  "E_Guanidinium_O_C9_SO3_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_O_C9_SO3_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_Guanidinium_O_C9_SO3_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "E_Guanidinium_O_C9_SO3_4 = ((B - D4) - (A - C4))*au2kcal;"
echo  "E_Guanidinium_O_C9_SO3_5 = ((B - D5) - (A - C5))*au2kcal;"
echo  "E_Guanidinium_O_C9_SO3_6 = ((B - D6) - (A - C6))*au2kcal;"
echo  "Electro_Guanidinium_O_C9_SO3 = -0.529*au2kcal/r;"
echo  "E_SB = [E_Guanidinium_O_C9_SO3_1 E_Guanidinium_O_C9_SO3_2 E_Guanidinium_O_C9_SO3_3 E_Guanidinium_O_C9_SO3_4 E_Guanidinium_O_C9_SO3_5 E_Guanidinium_O_C9_SO3_6];"
echo  "E_Guanidinium_O_C9_SO3_TC = mean(E_SB) %+ Electro_Guanidinium_O_C9_SO3"
echo  "% Guanidinium_C3_SO3_comp   "
  B=$(grep -B6 'ORCA prop' C3L1A3/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C3L1A3/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C3L1A3/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C3L1A3/D3.out | grep FINAL | awk {'print $NF'})
 D4=$(grep -B6 'ORCA prop' C3L1A3/D4.out | grep FINAL | awk {'print $NF'})
 D5=$(grep -B6 'ORCA prop' C3L1A3/D5.out | grep FINAL | awk {'print $NF'})
 D6=$(grep -B6 'ORCA prop' C3L1A3/D6.out | grep FINAL | awk {'print $NF'})
 D7=$(grep -B6 'ORCA prop' C3L1A3/D7.out | grep FINAL | awk {'print $NF'})
 D8=$(grep -B6 'ORCA prop' C3L1A3/D8.out | grep FINAL | awk {'print $NF'})
 D9=$(grep -B6 'ORCA prop' C3L1A3/D9.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C3L1A3/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C3L1A3/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C3L1A3/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C3L1A3/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C3L1A3/C2_pos.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C3L1A3/C2_neg.out | grep FINAL | awk {'print $NF'})
C3p=$(grep -B6 'ORCA prop' C3L1A3/C3_pos.out | grep FINAL | awk {'print $NF'})
C3m=$(grep -B6 'ORCA prop' C3L1A3/C3_neg.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  "D4 = $D4;"
echo  "D5 = $D5;"
echo  "D6 = $D6;"
echo  "D7 = $D7;"
echo  "D8 = $D8;"
echo  "D9 = $D9;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C2p $C1m;"
echo  "C3 = $C3p $C1m;"
echo  "C4 = $C1p $C2m;"
echo  "C5 = $C2p $C2m;"
echo  "C6 = $C3p $C2m;"
echo  "C7 = $C1p $C3m;"
echo  "C8 = $C2p $C3m;"
echo  "C9 = $C3p $C3m;"
echo  " r = 6.442;"
echo  "E_Guanidinium_C3_SO3_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_C3_SO3_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_Guanidinium_C3_SO3_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "E_Guanidinium_C3_SO3_4 = ((B - D4) - (A - C4))*au2kcal;"
echo  "E_Guanidinium_C3_SO3_5 = ((B - D5) - (A - C5))*au2kcal;"
echo  "E_Guanidinium_C3_SO3_6 = ((B - D6) - (A - C6))*au2kcal;"
echo  "E_Guanidinium_C3_SO3_7 = ((B - D7) - (A - C7))*au2kcal;"
echo  "E_Guanidinium_C3_SO3_8 = ((B - D8) - (A - C8))*au2kcal;"
echo  "E_Guanidinium_C3_SO3_9 = ((B - D9) - (A - C9))*au2kcal;"
echo  "Electro_Guanidinium_C3_SO3 = -0.529*au2kcal/r;"
echo  "E_SB = [E_Guanidinium_C3_SO3_1 E_Guanidinium_C3_SO3_2 E_Guanidinium_C3_SO3_3 E_Guanidinium_C3_SO3_4 E_Guanidinium_C3_SO3_5 E_Guanidinium_C3_SO3_6 E_Guanidinium_C3_SO3_7 E_Guanidinium_C3_SO3_8 E_Guanidinium_C3_SO3_9];"
echo  "E_Guanidinium_C3_SO3_TC = mean(E_SB) %+ Electro_Guanidinium_C3_SO3"
echo  "% Guanidinium_C6_SO3_comp"
  B=$(grep -B6 'ORCA prop' C3L2A3/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C3L2A3/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C3L2A3/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C3L2A3/D3.out | grep FINAL | awk {'print $NF'})
 D4=$(grep -B6 'ORCA prop' C3L2A3/D4.out | grep FINAL | awk {'print $NF'})
 D5=$(grep -B6 'ORCA prop' C3L2A3/D5.out | grep FINAL | awk {'print $NF'})
 D6=$(grep -B6 'ORCA prop' C3L2A3/D6.out | grep FINAL | awk {'print $NF'})
 D7=$(grep -B6 'ORCA prop' C3L2A3/D7.out | grep FINAL | awk {'print $NF'})
 D8=$(grep -B6 'ORCA prop' C3L2A3/D8.out | grep FINAL | awk {'print $NF'})
 D9=$(grep -B6 'ORCA prop' C3L2A3/D9.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C3L2A3/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C3L2A3/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C3L2A3/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C3L2A3/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C3L2A3/C2_pos.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C3L2A3/C2_neg.out | grep FINAL | awk {'print $NF'})
C3p=$(grep -B6 'ORCA prop' C3L2A3/C3_pos.out | grep FINAL | awk {'print $NF'})
C3m=$(grep -B6 'ORCA prop' C3L2A3/C3_neg.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  "D4 = $D4;"
echo  "D5 = $D5;"
echo  "D6 = $D6;"
echo  "D7 = $D7;"
echo  "D8 = $D8;"
echo  "D9 = $D9;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C2p $C1m;"
echo  "C3 = $C3p $C1m;"
echo  "C4 = $C1p $C2m;"
echo  "C5 = $C2p $C2m;"
echo  "C6 = $C3p $C2m;"
echo  "C7 = $C1p $C3m;"
echo  "C8 = $C2p $C3m;"
echo  "C9 = $C3p $C3m;"
echo  "E_Guanidinium_C6_SO3_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_C6_SO3_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_Guanidinium_C6_SO3_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "E_Guanidinium_C6_SO3_4 = ((B - D4) - (A - C4))*au2kcal;"
echo  "E_Guanidinium_C6_SO3_5 = ((B - D5) - (A - C5))*au2kcal;"
echo  "E_Guanidinium_C6_SO3_6 = ((B - D6) - (A - C6))*au2kcal;"
echo  "E_Guanidinium_C6_SO3_7 = ((B - D7) - (A - C7))*au2kcal;"
echo  "E_Guanidinium_C6_SO3_8 = ((B - D8) - (A - C8))*au2kcal;"
echo  "E_Guanidinium_C6_SO3_9 = ((B - D9) - (A - C9))*au2kcal;"
echo  " r = 10.223;"
echo  "E_Guanidinium_C6_SO3 = ((B - D) - (A - C))*au2kcal;"
echo  "Electro_Guanidinium_C6_SO3 = -0.529*au2kcal/r;"
echo  "E_SB = [E_Guanidinium_C6_SO3_1 E_Guanidinium_C6_SO3_2 E_Guanidinium_C6_SO3_3 E_Guanidinium_C6_SO3_4 E_Guanidinium_C6_SO3_5 E_Guanidinium_C6_SO3_6 E_Guanidinium_C6_SO3_7 E_Guanidinium_C6_SO3_8 E_Guanidinium_C6_SO3_9];"
echo  "E_Guanidinium_C6_SO3_TC = mean(E_SB) %+ Electro_Guanidinium_C6_SO3"
echo  "% Guanidinium_C9_SO3_comp     "
  B=$(grep -B6 'ORCA prop' C3L3A3/B.out | grep FINAL | awk {'print $NF'})
 D1=$(grep -B6 'ORCA prop' C3L3A3/D1.out | grep FINAL | awk {'print $NF'})
 D2=$(grep -B6 'ORCA prop' C3L3A3/D2.out | grep FINAL | awk {'print $NF'})
 D3=$(grep -B6 'ORCA prop' C3L3A3/D3.out | grep FINAL | awk {'print $NF'})
 D4=$(grep -B6 'ORCA prop' C3L3A3/D4.out | grep FINAL | awk {'print $NF'})
 D5=$(grep -B6 'ORCA prop' C3L3A3/D5.out | grep FINAL | awk {'print $NF'})
 D6=$(grep -B6 'ORCA prop' C3L3A3/D6.out | grep FINAL | awk {'print $NF'})
 D7=$(grep -B6 'ORCA prop' C3L3A3/D7.out | grep FINAL | awk {'print $NF'})
 D8=$(grep -B6 'ORCA prop' C3L3A3/D8.out | grep FINAL | awk {'print $NF'})
 D9=$(grep -B6 'ORCA prop' C3L3A3/D9.out | grep FINAL | awk {'print $NF'})
 Ap=$(grep -B6 'ORCA prop' C3L3A3/A_pos.out | grep FINAL | awk {'print $NF'})
 Am=$(grep -B6 'ORCA prop' C3L3A3/A_neg.out | grep FINAL | awk {'print $NF'})
C1p=$(grep -B6 'ORCA prop' C3L3A3/C1_pos.out | grep FINAL | awk {'print $NF'})
C1m=$(grep -B6 'ORCA prop' C3L3A3/C1_neg.out | grep FINAL | awk {'print $NF'})
C2p=$(grep -B6 'ORCA prop' C3L3A3/C2_pos.out | grep FINAL | awk {'print $NF'})
C2m=$(grep -B6 'ORCA prop' C3L3A3/C2_neg.out | grep FINAL | awk {'print $NF'})
C3p=$(grep -B6 'ORCA prop' C3L3A3/C3_pos.out | grep FINAL | awk {'print $NF'})
C3m=$(grep -B6 'ORCA prop' C3L3A3/C3_neg.out | grep FINAL | awk {'print $NF'})
echo  " B = $B;"
echo  "D1 = $D1;"
echo  "D2 = $D2;"
echo  "D3 = $D3;"
echo  "D4 = $D4;"
echo  "D5 = $D5;"
echo  "D6 = $D6;"
echo  "D7 = $D7;"
echo  "D8 = $D8;"
echo  "D9 = $D9;"
echo  " A = $Ap $Am;"
echo  "C1 = $C1p $C1m;"
echo  "C2 = $C2p $C1m;"
echo  "C3 = $C3p $C1m;"
echo  "C4 = $C1p $C2m;"
echo  "C5 = $C2p $C2m;"
echo  "C6 = $C3p $C2m;"
echo  "C7 = $C1p $C3m;"
echo  "C8 = $C2p $C3m;"
echo  "C9 = $C3p $C3m;"
echo  "E_Guanidinium_C9_SO3_1 = ((B - D1) - (A - C1))*au2kcal;"
echo  "E_Guanidinium_C9_SO3_2 = ((B - D2) - (A - C2))*au2kcal;"
echo  "E_Guanidinium_C9_SO3_3 = ((B - D3) - (A - C3))*au2kcal;"
echo  "E_Guanidinium_C9_SO3_4 = ((B - D4) - (A - C4))*au2kcal;"
echo  "E_Guanidinium_C9_SO3_5 = ((B - D5) - (A - C5))*au2kcal;"
echo  "E_Guanidinium_C9_SO3_6 = ((B - D6) - (A - C6))*au2kcal;"
echo  "E_Guanidinium_C9_SO3_7 = ((B - D7) - (A - C7))*au2kcal;"
echo  "E_Guanidinium_C9_SO3_8 = ((B - D8) - (A - C8))*au2kcal;"
echo  "E_Guanidinium_C9_SO3_9 = ((B - D9) - (A - C9))*au2kcal;"
echo  " r = 14.028;"
echo  "Electro_Guanidinium_C9_SO3 = -0.529*au2kcal/r;"
echo  "E_SB = [E_Guanidinium_C9_SO3_1 E_Guanidinium_C9_SO3_2 E_Guanidinium_C9_SO3_3 E_Guanidinium_C9_SO3_4 E_Guanidinium_C9_SO3_5 E_Guanidinium_C9_SO3_6 E_Guanidinium_C9_SO3_7 E_Guanidinium_C9_SO3_8 E_Guanidinium_C9_SO3_9];"
echo  "E_Guanidinium_C9_SO3_TC = mean(E_SB) %+ Electro_Guanidinium_C9_SO3"
